"""add year

Revision ID: 2174c4168bd9
Revises: c1d480326883
Create Date: 2026-03-13 10:25:40.432512

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2174c4168bd9'
down_revision = 'c1d480326883'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'year')
    # ### end Alembic commands ###
